server:
  port: 8080
  servlet:
    context-path: /onebot
    encoding:
      charset: utf-8
  tomcat:
    threads:
      max: 16
  undertow:
    url-charset: UTF-8
    threads:
      io: 16
      worker: 16

spring:
  threads:
    virtual:
      enabled: true

onebot:
  config:
    authorization: kSLuTF2GC2Q4q4ugm3
    timeout: 120000
    plugin-list:
      - com.github.onebot.plugin.DemoPlugin
  thread:
    core-pool-size: 5
    max-pool-size: 20
    keep-alive-time: 2000
    work-queue-size: 512
